/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.dao;
import beans.Agenda;
import beans.Clientes;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author julia
 */
public class agenda extends javax.swing.JFrame {

    /**
     * Creates new form agenda
     */
    public agenda() {
        initComponents();
        jLabel1.setOpaque(true);
        jLabel1.setBackground(new java.awt.Color(255, 182, 193));
        jLabel1.setForeground(java.awt.Color.BLACK);
        jPanel1.setToolTipText("Insira os dados para a agenda");
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdata = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfuncionarios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtservicos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("Insira os dados para marcar uma sessão");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                                       AGENDA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setLabelFor(txtcliente);
        jLabel2.setText("Cliente:");

        txtcliente.setText(" ");
        txtcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setLabelFor(txtdata);
        jLabel3.setText("Data:");

        txtdata.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setLabelFor(txtfuncionarios);
        jLabel4.setText(" Funcionários:");

        txtfuncionarios.setText(" ");
        txtfuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfuncionariosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setLabelFor(txthora);
        jLabel6.setText("Hora:");

        txthora.setText(" ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setLabelFor(txtservicos);
        jLabel7.setText("Serviços:");

        txtservicos.setText(" ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("AGENDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Data", "Hora", "Cliente", "Funcionário", "Serviços"
            }
        ));
        jScrollPane1.setViewportView(lista);
        lista.getAccessibleContext().setAccessibleName("lista de agendamentos");
        lista.getAccessibleContext().setAccessibleDescription("lista com os agendamentos");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Funcionários");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtservicos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtfuncionarios))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthora, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtservicos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );

        jLabel1.getAccessibleContext().setAccessibleName("  AGENDA");
        jLabel1.getAccessibleContext().setAccessibleDescription("Tela de agenda");
        jLabel2.getAccessibleContext().setAccessibleName("Cliente");
        jLabel2.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o nome do cliente");
        txtcliente.getAccessibleContext().setAccessibleName("Cliente");
        txtcliente.getAccessibleContext().setAccessibleDescription("Escreva o nome do Cliente aqui");
        jLabel3.getAccessibleContext().setAccessibleName("Data");
        jLabel3.getAccessibleContext().setAccessibleDescription("Indicando onde colocar a data");
        txtdata.getAccessibleContext().setAccessibleName("Data");
        txtdata.getAccessibleContext().setAccessibleDescription("Escreva a data aqui");
        jLabel4.getAccessibleContext().setAccessibleName(" Funcionários");
        jLabel4.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o nime do Funcionário");
        txtfuncionarios.getAccessibleContext().setAccessibleName(" Funcionários");
        txtfuncionarios.getAccessibleContext().setAccessibleDescription("Escreva o nome dos funcionários aqui");
        jLabel6.getAccessibleContext().setAccessibleName("Hora");
        jLabel6.getAccessibleContext().setAccessibleDescription("Indicando aonde escrever a hora");
        txthora.getAccessibleContext().setAccessibleName("Hora");
        txthora.getAccessibleContext().setAccessibleDescription("Escreva o nome a hora");
        jLabel7.getAccessibleContext().setAccessibleName("Serviços");
        jLabel7.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o serviço");
        txtservicos.getAccessibleContext().setAccessibleName("Serviços");
        txtservicos.getAccessibleContext().setAccessibleDescription("Escreva os serviços");
        jButton1.getAccessibleContext().setAccessibleDescription("Clique para agendar");
        jButton2.getAccessibleContext().setAccessibleDescription("Clique para ir a tela de Clientes");
        jButton3.getAccessibleContext().setAccessibleDescription("Clique para ir a tela de venda");

        getAccessibleContext().setAccessibleName("Tela de agenda");
        getAccessibleContext().setAccessibleDescription("Marque sessões");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfuncionariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        passarDados(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclienteActionPerformed
        // TODO add .getText(your handling code here:
    }//GEN-LAST:event_txtclienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        venda venda = new venda();
        venda.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Funcionarios f = new Funcionarios();
        f.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtfuncionarios;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtservicos;
    // End of variables declaration//GEN-END:variables
public void passarDados(java.awt.event.ActionEvent evt) {
        String cliente = txtcliente.getText().trim();
        String data = txtdata.getText().trim();
        String funcionarios = txtfuncionarios.getText().trim();
        String hora = txthora.getText().trim();
        String servicos = txtservicos.getText().trim();

        if (cliente.isEmpty() || data.isEmpty() || funcionarios.isEmpty() || hora.isEmpty() || servicos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        } else {
            boolean clienteV = cliente.matches("^[A-Za-zÀ-ÿ]+(?: [A-Za-zÀ-ÿ]+)+$");
            boolean dataV = data.matches("[0-9]{2}/[0-9]{2}/[0-9]{4}");
            boolean funcionariosV = funcionarios.matches("^[A-Za-zÀ-ÿ]+(?: [A-Za-zÀ-ÿ]+)*$");
            boolean horaV = hora.matches("^(?:[01]\\d|2[0-3]):[0-5]\\d$");
            boolean servicosV = servicos.matches("^[A-Za-zÀ-ÿ0-9\\s,.-]+$");

            StringBuilder erro = new StringBuilder();

            if (!clienteV) {
                erro.append("- Nome do cliente inválido! Exemplo: João Silva\n");
            }
            if (!dataV) {
                erro.append("- Data inválida! Formato esperado: dd/mm/aaaa. Exemplo: 25/12/2000\n");
            }
            if (!funcionariosV) {
                erro.append("- Nome do funcionário inválido! Exemplo: Maria Souza\n");
            }
            if (!horaV) {
                erro.append("- Hora inválida! Formato esperado: HH:mm. Exemplo: 14:30\n");
            }
            if (!servicosV) {
                erro.append("- Serviço inválido! Exemplo: Corte de cabelo, Manicure\n");
            }

            if (erro.length() > 0) {
                JOptionPane.showMessageDialog(null, "Corrija os seguintes erros:\n\n" + erro.toString(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                dao da = new dao();
                boolean clienteb = da.clienteExiste(cliente);
                boolean funcionariob = da.funcionarioExiste(funcionarios);
                double servicob = da.servicoExiste(servicos);
                StringBuilder errob = new StringBuilder();
                if (!clienteb) {
                    errob.append("Cliente não encontrado");
                }
                if (!funcionariob) {
                    errob.append("Funcionário não encontrado");
                }
                if (servicob < 0) {
                    errob.append("Serviço não encontrado");
                }
                if (errob.length() > 0) {
                  JOptionPane.showMessageDialog(null, "Seguintes informações não encontradas" + errob.toString(), "Erro de identifição", JOptionPane.ERROR_MESSAGE);  
                }else{
                    Agenda agenda = new Agenda();
                    setarData(agenda , data);
                    agenda.setFuncionario(funcionarios);
                    agenda.setHora(hora);
                    agenda.setNomeCliente(cliente);
                    agenda.setNomeServico(servicos);
                    agenda.setValor(da.servicoExiste(servicos));
                    da.inserirA(agenda);
                    txtcliente.setText(" ");
                    txtfuncionarios.setText(" ");
                    txtdata.setText(" ");
                    txthora.setText(" ");
                    txtservicos.setText(" ");
                    preencherTabela();
                }
            }
        }
    }

    private void preencherTabela() {
        dao da = new dao();
        List<Agenda> ListaAgenda = da.getAgenda();
        DefaultTableModel tabelaagenda = (DefaultTableModel) lista.getModel();
        tabelaagenda.setNumRows(0);
        lista.setRowSorter(new TableRowSorter(tabelaagenda));
        for (Agenda c : ListaAgenda) {
            Object[] obj = new Object[]{
                c.getData(),
                c.getHora(),
                c.getNomeCliente(),
                c.getFuncionario(),
                c.getNomeServico(),};
            tabelaagenda.addRow(obj);
        }
    }
   public void setarData(Agenda agenda, String data) {
    try {
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = formatoEntrada.parse(data);
        agenda.setData(dataFormatada);   
    } catch (ParseException e) {
        e.printStackTrace(); 
    }
}
}
