/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.dao;
import beans.Agenda;
import beans.Clientes;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        jlabel1.setOpaque(true);
        jlabel1.setBackground(new java.awt.Color(255, 182, 193));
        jlabel1.setForeground(java.awt.Color.BLACK);
        jPanel1.setToolTipText("Insira os dados do cliente para cadastro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtalergia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaniversario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        agenda = new javax.swing.JButton();
        venda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("Insira os dados do cliente para cadastro");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 255, 255));
        jlabel1.setText("                                     Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setLabelFor(txtnome);
        jLabel2.setText("Nome:");

        txtnome.setText(" ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setLabelFor(txttelefone);
        jLabel3.setText("Telefone:");

        txttelefone.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setLabelFor(txtalergia);
        jLabel4.setText("Alergia:");

        txtalergia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtalergia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setLabelFor(txtemail);
        jLabel5.setText("Email:");

        txtemail.setText(" ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setLabelFor(txtcpf);
        jLabel6.setText("CPF:");

        txtcpf.setText(" ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setLabelFor(txtaniversario);
        jLabel7.setText("Aniversário:");

        txtaniversario.setText(" ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setLabelFor(txtendereco);
        jLabel1.setText("Endereço:");

        txtendereco.setText(" ");

        cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        agenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agenda.setText("Agenda");
        agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaActionPerformed(evt);
            }
        });

        venda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtalergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(venda, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtaniversario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalergia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaniversario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Tela dos Clientes");
        jLabel2.getAccessibleContext().setAccessibleName("Nome ");
        jLabel2.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o nome do Cliente");
        txtnome.getAccessibleContext().setAccessibleName("Nome ");
        txtnome.getAccessibleContext().setAccessibleDescription("Escreva o nome do cliente");
        jButton1.getAccessibleContext().setAccessibleDescription("Clique para pesquisar o nome do cliente");
        jLabel3.getAccessibleContext().setAccessibleName("Telefone ");
        jLabel3.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o número de telefone");
        txttelefone.getAccessibleContext().setAccessibleName("Telefone ");
        txttelefone.getAccessibleContext().setAccessibleDescription("Escreva o telefone");
        jLabel4.getAccessibleContext().setAccessibleName("Alergia ");
        jLabel4.getAccessibleContext().setAccessibleDescription("indicando onde selecionar ");
        txtalergia.getAccessibleContext().setAccessibleName("Alergia ");
        txtalergia.getAccessibleContext().setAccessibleDescription("Selecione se o cliente possui alergia");
        jLabel5.getAccessibleContext().setAccessibleName("Email ");
        jLabel5.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o email");
        txtemail.getAccessibleContext().setAccessibleName("Email ");
        txtemail.getAccessibleContext().setAccessibleDescription("Escreva o email");
        jLabel6.getAccessibleContext().setAccessibleName("CPF ");
        jLabel6.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o cpf");
        jLabel7.getAccessibleContext().setAccessibleName("Aniversário ");
        jLabel7.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o aniversario");
        txtaniversario.getAccessibleContext().setAccessibleName("Aniversário ");
        txtaniversario.getAccessibleContext().setAccessibleDescription("Escreva o aniversário do cliente");
        jLabel1.getAccessibleContext().setAccessibleName("Endereço ");
        jLabel1.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o endereço");
        txtendereco.getAccessibleContext().setAccessibleName("Endereço ");
        txtendereco.getAccessibleContext().setAccessibleDescription("Escreva o endereço ");
        cadastrar.getAccessibleContext().setAccessibleDescription("Clique para cadastrar");
        agenda.getAccessibleContext().setAccessibleDescription("Clique para ir a tela de agendas");
        venda.getAccessibleContext().setAccessibleDescription("Clique para ir a tela de vendas");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        passardados(evt);

    }//GEN-LAST:event_cadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        venda v = new venda();
        v.setVisible(true);
    }//GEN-LAST:event_vendaActionPerformed

    private void agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaActionPerformed
        agenda a = new agenda();
        a.setVisible(true);
    }//GEN-LAST:event_agendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agenda;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JComboBox<String> txtalergia;
    private javax.swing.JTextField txtaniversario;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    private javax.swing.JButton venda;
    // End of variables declaration//GEN-END:variables
public void passardados(java.awt.event.ActionEvent evt) {
        String nome = txtnome.getText().trim();
        String telefone = txttelefone.getText().trim();
        String email = txtemail.getText().trim();
        String cpf = txtcpf.getText().trim();
        String data = txtaniversario.getText().trim();
        String endereco = txtendereco.getText().trim();

        if (nome.isEmpty() || telefone.isEmpty() || email.isEmpty() || cpf.isEmpty() || data.isEmpty() || endereco.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        } else {
            boolean nomev = nome.matches("^[A-Za-zÀ-ÿ]+(?: [A-Za-zÀ-ÿ]+)+$");
            boolean telefonev = telefone.matches("\\d{4,5}-\\d{4}");
            boolean emailv = email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
            boolean cpfv = cpf.matches("\\d{11}");
            boolean datav = data.matches("[0-9]{2}/[0-9]{2}/[0-9]{4}");
            boolean enderecov = endereco.matches("^[A-Za-zÀ-ÿ0-9\\s,.ºª-]+$");

            StringBuilder erro = new StringBuilder();

            if (!nomev) {
                erro.append("- Nome inválido! Exemplo: João Silva\n");
            }
            if (!telefonev) {
                erro.append("- Telefone inválido! Formato esperado: 99999-9999\n");
            }
            if (!emailv) {
                erro.append("- Email inválido! Exemplo: exemplo@email.com\n");
            }
            if (!cpfv) {
                erro.append("- CPF inválido! Deve conter 11 dígitos numéricos. Exemplo: 12345678901\n");
            }
            if (!datav) {
                erro.append("- Data inválida! Formato esperado: dd/mm/aaaa. Exemplo: 25/12/2000\n");
            }
            if (!enderecov) {
                erro.append("- Endereço inválido! Exemplo: Rua das Flores, 123 - Centro, São Paulo - SP, 01000-000\n");
            }

            if (erro.length() > 0) {
                JOptionPane.showMessageDialog(null, "Corrija os seguintes erros:\n\n" + erro.toString(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                String alergia = String.valueOf(txtalergia.getSelectedItem());
                JOptionPane.showMessageDialog(null, "Dados validados com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                Clientes cliente = new Clientes();
                cliente.setNome(nome);
                cliente.setTelefone(telefone);
                cliente.setEmail(email);
                cliente.setCpf(cpf);
                cliente.setEndereco(endereco);
                setarData(cliente , data);
                cliente.setAlergia(alergia);
                dao da = new dao();
                da.inserirC(cliente);
                txtnome.setText(" ");
                txtemail.setText(" ");
                txttelefone.setText(" ");
                txtcpf.setText(" ");
                txtendereco.setText(" ");
                txtaniversario.setText(" ");
                txtalergia.setSelectedItem(null);
            }

        }
    }

    public void pesquisar() {
    txtemail.setText(" ");
    txttelefone.setText(" ");
    txtcpf.setText(" ");
    txtendereco.setText(" ");
    txtaniversario.setText(" ");
    txtalergia.setSelectedItem(null);

    String nome = txtnome.getText().trim();
    Clientes cliente = new Clientes();
    dao da = new dao();
    
     
    cliente = da.getClienteNome(nome);

     
    if (cliente != null) {
        txtemail.setText(cliente.getEmail());
        txttelefone.setText(cliente.getTelefone());
        txtcpf.setText(cliente.getCpf());
        txtendereco.setText(cliente.getEndereco());

         
        if (cliente.getAniversario() != null) {
            txtaniversario.setText(new SimpleDateFormat("dd/MM/yyyy").format(cliente.getAniversario()));
        } else {
            txtaniversario.setText("");  
        }

        txtalergia.setSelectedItem(cliente.getAlergia());
    } else {
        JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
    }
}


    public void setarData(Clientes cliente, String data) {
    try {
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = formatoEntrada.parse(data);
        cliente.setAniversario(dataFormatada);   
    } catch (ParseException e) {
        e.printStackTrace(); 
    }
}
}
