/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.dao;
import beans.Clientes;
import beans.funcionarios;
import beans.produtos;
import beans.servicos;
import beans.vendas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class venda extends javax.swing.JFrame {

    /**
     * Creates new form venda
     */
    public venda() {
        initComponents();
        jLabel1.setOpaque(true);
        jLabel1.setBackground(new java.awt.Color(255, 182, 193));
        jLabel1.setForeground(java.awt.Color.BLACK);
        jPanel1.setToolTipText("Insira os dados para a venda");
        txtprodutos.setEnabled(false);
        txtservicos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfuncionarios = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtservicos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtprodutos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("Insira os dados das vendas");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                           VENDAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setLabelFor(txtcliente);
        jLabel2.setText("Clientes:");

        txtcliente.setText(" ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setLabelFor(txtData);
        jLabel3.setText(" Data:");

        txtData.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setLabelFor(txtfuncionarios);
        jLabel4.setText("Funcionários:");

        txtfuncionarios.setText(" ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setLabelFor(txthora);
        jLabel5.setText("Hora:");

        txthora.setText(" ");

        comboTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serviços", "Produtos", "Serviços e Produtos" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setLabelFor(comboTipo);
        jLabel6.setText("Tipo de vendas:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setLabelFor(txtservicos);
        jLabel7.setText("Serviços:");

        txtservicos.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setLabelFor(txtprodutos);
        jLabel8.setText("Produtos:");

        txtprodutos.setText(" ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Agenda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Listagem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Clientes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfuncionarios))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtservicos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txthora))
                            .addComponent(txtprodutos)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(114, 114, 114)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfuncionarios)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtservicos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("tela de vendas");
        jPanel1.getAccessibleContext().setAccessibleDescription("registre suas vendas");
        jLabel1.getAccessibleContext().setAccessibleDescription("vendas");
        jLabel2.getAccessibleContext().setAccessibleName("Clientes ");
        jLabel2.getAccessibleContext().setAccessibleDescription("Indicando onde esvrever o nome do cliente");
        txtcliente.getAccessibleContext().setAccessibleName("Nome Cliente");
        txtcliente.getAccessibleContext().setAccessibleDescription("Escreva o nome do Cliente");
        jLabel3.getAccessibleContext().setAccessibleName("data");
        jLabel3.getAccessibleContext().setAccessibleDescription("Indicando onde escrever a data");
        jLabel4.getAccessibleContext().setAccessibleName("Funcionários ");
        jLabel4.getAccessibleContext().setAccessibleDescription("Indicando onde escrever o nome dos funcionários");
        jLabel5.getAccessibleContext().setAccessibleName("Hora ");
        jLabel5.getAccessibleContext().setAccessibleDescription("Indicando onde escrever a hora");
        txthora.getAccessibleContext().setAccessibleName("Hora ");
        txthora.getAccessibleContext().setAccessibleDescription("Escreva a hora");
        comboTipo.getAccessibleContext().setAccessibleName("Tipo de vendas ");
        comboTipo.getAccessibleContext().setAccessibleDescription("Selecione o tipo de venda");
        jLabel6.getAccessibleContext().setAccessibleName("Tipo de vendas ");
        jLabel6.getAccessibleContext().setAccessibleDescription("Indicando onde selecionar o tipo de venda");
        jLabel7.getAccessibleContext().setAccessibleName("Serviços ");
        jLabel7.getAccessibleContext().setAccessibleDescription("Indicando onde escrever os serviços");
        txtservicos.getAccessibleContext().setAccessibleName("Serviços ");
        txtservicos.getAccessibleContext().setAccessibleDescription("Escreva os serviços");
        jLabel8.getAccessibleContext().setAccessibleName("Produtos ");
        jLabel8.getAccessibleContext().setAccessibleDescription("Indicando onde escrever os nomes dos produtos");
        txtprodutos.getAccessibleContext().setAccessibleName("Produtos ");
        txtprodutos.getAccessibleContext().setAccessibleDescription("Escreva o nome dos produtos");
        jButton1.getAccessibleContext().setAccessibleDescription("Clique para cadastrar");
        jButton2.getAccessibleContext().setAccessibleDescription("Clique para ir para a tela de agenda");
        jButton3.getAccessibleContext().setAccessibleDescription("Clique para ir para a tela de listagem");
        jButton4.getAccessibleContext().setAccessibleDescription("Clique para ir para atela de Clientes");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        String selected = (String) comboTipo.getSelectedItem();

        if ("Serviços".equals(selected)) {
            txtservicos.setEnabled(true);
            txtprodutos.setEnabled(false);
            txtprodutos.setText("");
        } else if ("Produtos".equals(selected)) {
            txtservicos.setEnabled(false);
            txtprodutos.setEnabled(true);
            txtservicos.setText("");
        } else if ("Serviços e Produtos".equals(selected)) {
            txtservicos.setEnabled(true);
            txtprodutos.setEnabled(true);
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      passarDados(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        agenda ag = new agenda();
        ag.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        listagem lista = new listagem();
        lista.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Cliente c = new Cliente();
        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtfuncionarios;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txtprodutos;
    private javax.swing.JTextField txtservicos;
    // End of variables declaration//GEN-END:variables
private void passarDados(java.awt.event.ActionEvent evt) {
        String data = txtData.getText().trim();
        String cliente = txtcliente.getText().trim();
        String funcionarios = txtfuncionarios.getText().trim();
        String hora = txthora.getText().trim();

        if (data.isEmpty() || cliente.isEmpty() || funcionarios.isEmpty() || hora.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean dataV = data.matches("\\d{2}/\\d{2}/\\d{4}");
            boolean clienteV = cliente.matches("^[A-Za-zÀ-ÿ]+(?: [A-Za-zÀ-ÿ]+)*$");
            boolean funcionariosV = funcionarios.matches("^[A-Za-zÀ-ÿ]+(?: [A-Za-zÀ-ÿ]+)*$");
            boolean horaV = hora.matches("^(?:[01]\\d|2[0-3]):[0-5]\\d$");

            StringBuilder erro = new StringBuilder();

            if (!dataV) {
                erro.append("- Data inválida! Formato esperado: dd/mm/aaaa. Exemplo: 25/12/2024\n");
            }
            if (!clienteV) {
                erro.append("- Nome do cliente inválido! Exemplo: João Silva\n");
            }
            if (!funcionariosV) {
                erro.append("- Nome do funcionário inválido! Exemplo: Maria Souza\n");
            }
            if (!horaV) {
                erro.append("- Hora inválida! Formato esperado: HH:mm. Exemplo: 14:30\n");
            }

            if (erro.length() > 0) {
                JOptionPane.showMessageDialog(null, "Corrija os seguintes erros:\n\n" + erro.toString(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                double valor = 0.0;
                dao da = new dao();
                double produto;
                double servico;
                String produtos = txtprodutos.getText().trim();
                String servicos = txtservicos.getText().trim();
                boolean clienteb = da.clienteExiste(cliente);
                boolean funcionariob = da.funcionarioExiste(funcionarios);

                StringBuilder errob = new StringBuilder();

                if (!clienteb) {
                    errob.append("Cliente não encontrado\n");
                }
                if (!funcionariob) {
                    errob.append("funcionario não encontrado\n");
                }
                if ("Serviços".equals(comboTipo.getSelectedItem())) {
                    servico = da.servicoExiste(servicos);
                    if (servico < 0) {
                        errob.append("Serviço não encontrado\n");
                    }
                    produtos = " ";
                    valor = servico;
                } else if ("Produtos".equals(comboTipo.getSelectedItem())) {
                    produto = da.produtoExiste(produtos);
                    if (produto < 0) {
                        errob.append("Produto não encontrado\n");
                    }
                    servicos = " ";
                    valor = produto;
                } else if ("Serviços e Produtos".equals(comboTipo.getSelectedItem())) {
                    servico = da.servicoExiste(servicos);
                    produto = da.produtoExiste(produtos);

                    if (servico < 0) {
                        errob.append("Serviço não encontrado\n");
                    }
                    if (produto < 0) {
                        errob.append("Produto não encontrado\n");
                    }
                    valor = servico + produto;

                }
                if (errob.length() > 0) {
                    JOptionPane.showMessageDialog(null, "Informações não encontradas\n" + erro.toString(), "Erro de identificação", JOptionPane.ERROR_MESSAGE);
                } else {
                    vendas v = new vendas();
                    setarData(v , data);
                    v.setFuncionario(funcionarios);
                    v.setHora(hora);
                    v.setNomeCliente(cliente);
                    v.setNomeProduto(produtos);
                    v.setNomeServico(servicos);
                    v.setValor(valor);
                    da.inserirV(v);
                    txtData.setText("");
                    txtcliente.setText("");
                    txtfuncionarios.setText("");
                    txthora.setText("");
                    txtprodutos.setText("");
                    txtservicos.setText("");
                }
            }
        }
    }
    public void setarData(vendas v, String data) {
    try {
        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = formatoEntrada.parse(data);
        v.setData(dataFormatada);   
    } catch (ParseException e) {
        e.printStackTrace(); 
    }
}
}
